// 本文件由 scripts/gen-content.mjs 生成，请勿手工编辑。
// 使用静态字符串字面量的动态 import，便于 bundler 做代码分割。
import type { ComponentType } from 'react'

type MdxModule = { default: ComponentType }

export const registry: Record<string, () => Promise<MdxModule>> = {
  "00-start/about": () => import("./00-start/about.mdx"),
  "00-start/getting-started": () => import("./00-start/getting-started.mdx"),
  "00-start/tour": () => import("./00-start/tour.mdx"),
  "01-basics/syntax-overview": () => import("./01-basics/syntax-overview.mdx"),
  "01-basics/val-var-null-safety": () => import("./01-basics/val-var-null-safety.mdx"),
  "01-basics/functions": () => import("./01-basics/functions.mdx"),
  "01-basics/idioms": () => import("./01-basics/idioms.mdx"),
  "01-basics/coding-conventions": () => import("./01-basics/coding-conventions.mdx"),
  "02-types/basic-types": () => import("./02-types/basic-types.mdx"),
  "02-types/strings": () => import("./02-types/strings.mdx"),
  "02-types/arrays": () => import("./02-types/arrays.mdx"),
  "02-types/type-checks-and-casts": () => import("./02-types/type-checks-and-casts.mdx"),
  "03-control-flow/conditions-and-loops": () => import("./03-control-flow/conditions-and-loops.mdx"),
  "03-control-flow/returns-and-jumps": () => import("./03-control-flow/returns-and-jumps.mdx"),
  "03-control-flow/exceptions": () => import("./03-control-flow/exceptions.mdx"),
  "04-classes/classes": () => import("./04-classes/classes.mdx"),
  "04-classes/inheritance": () => import("./04-classes/inheritance.mdx"),
  "04-classes/properties": () => import("./04-classes/properties.mdx"),
  "04-classes/interfaces": () => import("./04-classes/interfaces.mdx"),
  "04-classes/visibility-modifiers": () => import("./04-classes/visibility-modifiers.mdx"),
  "04-classes/extensions": () => import("./04-classes/extensions.mdx"),
  "04-classes/data-classes": () => import("./04-classes/data-classes.mdx"),
  "04-classes/sealed-classes": () => import("./04-classes/sealed-classes.mdx"),
  "04-classes/generics": () => import("./04-classes/generics.mdx"),
  "04-classes/enum-classes": () => import("./04-classes/enum-classes.mdx"),
  "04-classes/value-classes": () => import("./04-classes/value-classes.mdx"),
  "04-classes/object-declarations": () => import("./04-classes/object-declarations.mdx"),
  "04-classes/delegation": () => import("./04-classes/delegation.mdx"),
  "05-functional/functions-advanced": () => import("./05-functional/functions-advanced.mdx"),
  "05-functional/lambdas": () => import("./05-functional/lambdas.mdx"),
  "05-functional/inline-functions": () => import("./05-functional/inline-functions.mdx"),
  "05-functional/operator-overloading": () => import("./05-functional/operator-overloading.mdx"),
  "06-null-safety/null-safety": () => import("./06-null-safety/null-safety.mdx"),
  "06-null-safety/equality": () => import("./06-null-safety/equality.mdx"),
  "06-null-safety/this-expressions": () => import("./06-null-safety/this-expressions.mdx"),
  "07-collections/overview": () => import("./07-collections/overview.mdx"),
  "07-collections/transformations": () => import("./07-collections/transformations.mdx"),
  "07-collections/grouping-sorting-aggregation": () => import("./07-collections/grouping-sorting-aggregation.mdx"),
  "07-collections/list-set-map": () => import("./07-collections/list-set-map.mdx"),
  "07-collections/sequences": () => import("./07-collections/sequences.mdx"),
  "07-collections/scope-functions": () => import("./07-collections/scope-functions.mdx"),
  "08-coroutines/async-overview": () => import("./08-coroutines/async-overview.mdx"),
  "08-coroutines/basics": () => import("./08-coroutines/basics.mdx"),
  "08-coroutines/cancellation-and-timeouts": () => import("./08-coroutines/cancellation-and-timeouts.mdx"),
  "08-coroutines/composing-suspending-functions": () => import("./08-coroutines/composing-suspending-functions.mdx"),
  "08-coroutines/context-and-dispatchers": () => import("./08-coroutines/context-and-dispatchers.mdx"),
  "08-coroutines/flow": () => import("./08-coroutines/flow.mdx"),
  "08-coroutines/channels": () => import("./08-coroutines/channels.mdx"),
  "08-coroutines/exception-handling": () => import("./08-coroutines/exception-handling.mdx"),
  "08-coroutines/shared-mutable-state": () => import("./08-coroutines/shared-mutable-state.mdx"),
  "08-coroutines/callback-interop": () => import("./08-coroutines/callback-interop.mdx"),
  "09-advanced/annotations": () => import("./09-advanced/annotations.mdx"),
  "09-advanced/reflection": () => import("./09-advanced/reflection.mdx"),
  "09-advanced/destructuring": () => import("./09-advanced/destructuring.mdx"),
  "09-advanced/type-safe-builders": () => import("./09-advanced/type-safe-builders.mdx"),
  "09-advanced/context-parameters": () => import("./09-advanced/context-parameters.mdx"),
  "10-jetpack/compose-foundations": () => import("./10-jetpack/compose-foundations.mdx"),
  "10-jetpack/compose-state": () => import("./10-jetpack/compose-state.mdx"),
  "10-jetpack/compose-stability": () => import("./10-jetpack/compose-stability.mdx"),
  "10-jetpack/modifier": () => import("./10-jetpack/modifier.mdx"),
  "10-jetpack/viewmodel-and-di": () => import("./10-jetpack/viewmodel-and-di.mdx"),
  "10-jetpack/data-layer": () => import("./10-jetpack/data-layer.mdx"),
  "10-jetpack/navigation": () => import("./10-jetpack/navigation.mdx"),
  "10-jetpack/testing": () => import("./10-jetpack/testing.mdx"),
  "appendix/java-to-kotlin": () => import("./appendix/java-to-kotlin.mdx"),
  "appendix/further-reading": () => import("./appendix/further-reading.mdx"),
}
